rizilmaharjan/hrm

- be/package-lock.json
- be/src/config/database.ts
- be/src/index.ts
- be/src/jobType/controller/index.ts
- be/src/jobType/index.ts
- be/src/jobType/repository/index.ts
- be/src/jobType/services/index.ts
- be/src/types/index.ts
- be/src/utils/index.ts
- fe/package-lock.json
- fe/package.json
- fe/src/App.tsx
- fe/src/components/Navbar.tsx
- fe/src/components/Sidebar.tsx
- fe/src/modal/AddJobType.tsx
- fe/src/modal/Delete.tsx
- fe/src/pages/Dashboard.tsx
- fe/src/pages/JobType.tsx
- fe/src/pages/ServiceEvent.tsx
- fe/src/pages/UserProfile.tsx
- fe/tailwind.config.js
Implemented frontend and backend for job-type feature including UI enhancements and API endpoints; ready for review.
> Feature: Add job-type

- be/src/allowance/controller/index.ts
- be/src/allowance/index.ts
- be/src/allowance/repository/index.ts
- be/src/allowance/services/index.ts
- be/src/auth/services/index.ts
- be/src/index.ts
- fe/package-lock.json
- fe/package.json
- fe/src/App.tsx
- fe/src/components/Sidebar.tsx
- fe/src/context/DataContext.tsx
- fe/src/layout/Private.tsx
- fe/src/main.tsx
- fe/src/modal/AddAllowance.tsx
- fe/src/modal/AddEvent.tsx
- fe/src/modal/Delete.tsx
- fe/src/pages/Allowance.tsx
- fe/src/pages/Login.tsx
- fe/src/pages/ServiceEvent.tsx
- fe/src/redux/hooks.ts
- fe/src/redux/store.ts
- fe/src/redux/user/userSlice.ts
Implemented frontend and backend functionality for allowance table, with integrated Redux Toolkit in the frontend
> Feature: Add allowance table and redux toolkit

- fe/src/layout/Private.tsx
- fe/src/pages/Dashboard.tsx
- fe/src/pages/Login.tsx
Fixed login redirection issue.
> Bugfix: Fix login redirection issue

- be/src/position/controller/index.ts
- be/src/position/index.ts
- be/src/position/repository/index.ts
- be/src/position/services/index.ts
- fe/package-lock.json
- fe/src/pages/Allowance.tsx
- fe/src/pages/JobType.tsx
Updated the sidebar and add the account list on the allowance table.
> Feature: Update sidebar and add account list 

- fe/src/components/modal/AddAllowance.tsx
- fe/src/components/modal/AddEvent.tsx
- fe/src/components/modal/AddJobType.tsx
- fe/src/pages/Allowance.tsx
- fe/src/pages/JobType.tsx
- fe/src/pages/ServiceEvent.tsx
Implemented close modal on outside click
> Feature: Add close modal on outside click

- be/package-lock.json
- be/package.json
- be/src/api/v1/helpers/rateLimit.ts
- be/src/index.ts
> Feature: Add rate limit for apis

- fe/package-lock.json
- fe/package.json
- fe/src/assets/svg/index.tsx
- fe/src/components/modal/AddAllowance.tsx
- fe/src/components/modal/AddEvent.tsx
- fe/src/components/modal/AddJobType.tsx
- fe/src/constants/index.ts
- fe/src/pages/Allowance.tsx
- fe/src/pages/JobType.tsx
- fe/src/pages/Login.tsx
- fe/src/pages/ServiceEvent.tsx
- fe/src/validations/allowance.schema.ts
- fe/src/validations/jobType.schema.ts
- fe/src/validations/login.schema.ts
- fe/src/validations/serviceEvent.schema.ts
Feature: Add client-side validation and export to pdf feature.
> Feature: Add client side validation and export to pdf

- fe/package-lock.json
- fe/package.json
- fe/src/pages/Allowance.tsx
- fe/src/pages/JobType.tsx
- fe/src/pages/ServiceEvent.tsx
- package-lock.json
Fixed typescript errors in frontend
> BugFix: Fix typescript errors

- be/src/api/v1/controllers/allowanceController.ts
- be/src/api/v1/controllers/serviceEventController.ts
- be/src/api/v1/interfaces/model.interface.ts
- be/src/api/v1/models/allowanceModel.ts
- be/src/api/v1/models/serviceEventModel.ts
- be/src/api/v1/validations/allowance.schema.ts
- be/src/api/v1/validations/jobType.schema.ts
- fe/package-lock.json
- fe/package.json
- fe/src/components/modal/AddAllowance.tsx
- fe/src/components/modal/AddEvent.tsx
- fe/src/components/modal/AddJobType.tsx
- fe/src/components/ui/Input.tsx
- fe/src/constants/index.ts
- fe/src/interfaces/types/allowance.types.ts
- fe/src/interfaces/types/serviceEvent.types.ts
- fe/src/pages/JobType.tsx
- fe/src/pages/Login.tsx
- fe/src/pages/ServiceEvent.tsx
- fe/src/validations/allowance.schema.ts
- fe/src/validations/jobType.schema.ts
- fe/src/validations/serviceEvent.schema.ts
Implemented react hook form and user validation
> Feature: Add react hook form and validation

- be/package-lock.json
- fe/package-lock.json
- fe/package.json
- fe/src/components/modal/AddAllowance.tsx
- fe/src/components/modal/AddEvent.tsx
- fe/src/components/modal/AddJobType.tsx
Fixed input field not clear after edit
> BugFix: Fix input field not clear after edit

- be/src/api/v1/controllers/authController.ts
- be/src/api/v1/models/authModel.ts
Implemented feature where plain text password is compared with encrypted password
> Feature: Add decrypt password

- fe/src/App.tsx
- fe/src/components/ui/Input.tsx
- fe/src/constants/index.ts
- fe/src/interfaces/types/login.types.ts
- fe/src/pages/Allowance.tsx
- fe/src/pages/Login.tsx
- fe/src/pages/ServiceEvent.tsx
- fe/src/validations/login.schema.ts
Fixed allowance table layout and enable login on Enter key press
> BugFix: Fix allowance table layout and enable login on Enter key press

- be/src/api/v1/controllers/authController.ts
- be/src/api/v1/helpers/rateLimit.ts
- be/src/api/v1/models/authModel.ts
- be/src/api/v1/routes/authRoutes.ts
- be/src/api/v1/services/auth.ts
- be/src/api/v1/validations/changePassword.schema.ts
- be/src/api/v1/validations/login.schema.ts
Implemented user change password
> Feature: Add user change password

- fe/src/components/Navbar.tsx
- fe/src/components/Sidebar.tsx
- fe/src/pages/ChangePassword.tsx
Fixed darkmode issue for sidebar and navbar.
> Bugfix: Fix dark mode

- fe/src/components/Navbar.tsx
Implemented profile dropdown modal close on outside click
> Feature: Add profile dropdown modal close on outside click

- fe/src/components/Sidebar.tsx
> Refactor: Remove logout from sidebar

- fe/src/pages/Employee.tsx
- fe/src/pages/ServiceEvent.tsx
Fixed capitalization issues in desc.  table cell
> BugFix: Fix capitalization in desc table cell

- fe/src/components/modal/AddAllowance.tsx
- fe/src/components/modal/AddEvent.tsx
- fe/src/components/modal/AddJobType.tsx
- fe/src/main.tsx
- fe/src/pages/Allowance.tsx
- fe/src/pages/JobType.tsx
- fe/src/pages/ServiceEvent.tsx
- fe/src/redux/edit/editSlice.ts
- fe/src/redux/store.ts
Migrated from context to redux toolkit for edit state
> Refactor:Migrate from context to redux for edit state

- fe/src/components/modal/AddAllowance.tsx
- fe/src/components/modal/AddEvent.tsx
- fe/src/components/modal/AddJobType.tsx
- fe/src/components/ui/Input.tsx
- fe/src/pages/Allowance.tsx
- fe/src/pages/JobType.tsx
Capitalize descriptions and disabled code field during edit in job type ,allowance and also utilized dispatch in jobtype page
> BugFix:  Capitalize descriptions, disable code field during edit, and utilize dispatch in JobType page

- fe/src/components/modal/AddAllowance.tsx
- fe/src/components/modal/AddEvent.tsx
- fe/src/components/modal/AddJobType.tsx
Added error handling for unique constraint in front end
> Feature: Add error handling for unique constraint

- fe/src/components/modal/AddAllowance.tsx
- fe/src/components/modal/AddEvent.tsx
- fe/src/components/modal/AddJobType.tsx
Fixing the bug where new network requests were triggered before the completion of previous ones when clicked enter
> BugFix: Fix sequential network request

- fe/src/pages/Allowance.tsx
- fe/src/pages/JobType.tsx
- fe/src/pages/Position.tsx
- fe/src/pages/ServiceEvent.tsx
Fixed issue where the loader's behavior was causing displacement of the navbar.
> BugFix:  Fix misbehaving loader causing navbar displacement

- fe/src/pages/Employee.tsx
Resolved issue where the loader's behavior was causing displacement of the navbar
> BugFix: Fix misbehaving loader causing navbar displacement

- fe/src/App.tsx
- fe/src/api/index.tsx
- fe/src/pages/Allowance.tsx
- fe/src/pages/JobType.tsx
- fe/src/pages/ServiceEvent.tsx
Added tanstack query to fetch datas
> Feature: Add tanstack query to fetch datas

- fe/src/components/Navbar.tsx
Fixed serving public directory files at root path warning
> BugFix: Fix serving public directory files at root path

- fe/src/pages/ServiceEvent.tsx
Fixed the alignment of th element of service event section from center to left
> BugFix: Fix alignment of th element from center to left

- be/src/api/v1/controllers/authController.ts
add expiration duration of 24 hrs for the cookie
> Feature: Add expiry date for cookie

- fe/src/components/Profile/ProfileMenu.tsx
- fe/src/pages/Employee.tsx
- fe/src/pages/UserProfile.tsx
- fe/src/routes/index.tsx
Fixed navigation of employees page section
> BugFix: Fix navigation for employees

- be/src/api/v1/models/authModel.ts
- be/src/api/v1/services/auth.ts
add role info when user logs in
> Feature: Add roles data when user logs in

- fe/src/App.tsx
- fe/src/layout/MainLayout.tsx
- fe/src/pages/Login.tsx
- fe/src/redux/user/userSlice.ts
Add role based login for HR and Employee
> Feature: Add role base login

- be/src/api/v1/controllers/applyLeaveController.ts
- be/src/api/v1/models/applyLeaveModel.ts
- be/src/api/v1/routes/applyLeaveRoutes.ts
- be/src/api/v1/services/applyLeaveService.ts
add date conversion api for eng-to-nep and nep-to-eng
> Feature: Add date conversion api

- be/src/api/v1/routes/employeeRoutes.ts
- fe/src/App.tsx
- fe/src/components/EmployeeSidebar.tsx
- fe/src/pages/ApplyLeave.tsx
- fe/src/routes/index.tsx
Form to apply leave by employee UI complete.
> Feature: Apply leave form complete in frontend

- be/src/api/v1/controllers/employeeController.ts
- be/src/api/v1/models/applyLeaveModel.ts
- be/src/api/v1/models/employeeModel.ts
- be/src/api/v1/services/employeeService.ts
- fe/src/api/index.tsx
- fe/src/components/Dropdown.tsx
- fe/src/pages/Employee.tsx
fix pagination issue for employees
> BugFix:Fix pagination for employees

- be/src/api/v1/controllers/applyLeaveController.ts
- be/src/api/v1/models/applyLeaveModel.ts
- fe/src/pages/ApplyLeave.tsx
Add date conversion from nep-to-eng and vice-versa
> Feature: Add date conversion from nep-to-eng and vice-versa

- be/src/api/v1/controllers/applyLeaveController.ts
- be/src/api/v1/models/applyLeaveModel.ts
- be/src/api/v1/routes/applyLeaveRoutes.ts
- be/src/api/v1/services/applyLeaveService.ts
add leave balance route and check leave balance before applying leave
> Feature: Add leave balance route

- be/src/api/v1/models/applyLeaveModel.ts
- fe/src/components/EmployeeSidebar.tsx
- fe/src/components/LeaveBalance.tsx
- fe/src/pages/ApplyLeave.tsx
- fe/src/pages/Attendance.tsx
- fe/src/redux/user/userSlice.ts
Refactor: Refactor form elements in apply leave.
> Refactor: Refactor form elements in apply leave

- be/src/api/v1/models/applyLeaveModel.ts
- fe/src/components/EmployeeSidebar.tsx
- fe/src/pages/Allowance.tsx
Bugfix: Fix neptoeng date conversion.
> Bugfix: Fix neptoeng date conversion

- be/src/api/v1/models/applyLeaveModel.ts
> BugFix: Fix apply leave route

- be/src/api/v1/models/applyLeaveModel.ts
- fe/src/pages/ApplyLeave.tsx
Feature: Integrate post API for apply leave.
> Feature: Integrate posit api for apply leave

- fe/src/pages/ApplyLeave.tsx
fix clear form when clicked submit button
> BugFix: Fix clear form when submit

- fe/src/components/Calendar.tsx
- fe/src/components/Notice.tsx
- fe/src/constants/index.ts
- fe/src/pages/Dashboard.tsx
Feature: Add calendar and notice section in dashboard.
> Feature: Add calendar and notice section in dashboard. 

- be/src/api/v1/models/applyLeaveModel.ts
- fe/src/components/Calendar.tsx
- fe/src/components/Notice.tsx
- fe/src/constants/index.ts
- fe/src/pages/ApplyLeave.tsx
- fe/src/pages/Attendance.tsx
- fe/src/pages/Dashboard.tsx
- fe/src/pages/LeaveRequest.tsx
- fe/src/routes/index.tsx
Feature: Display leave applications of an employee.
> Feature: Visualize leave applications.
